# Example

default_model: llama3.1

llm_models:
  - llama3.1

embedding_model: bge-m3

sparse_model: Qdrant/bm42-all-minilm-l6-v2-attentions

qdrant_url: http://localhost:6333

ollama_url: http://localhost:11434
